### ISSUE TITLE
Investigate impact of increasing GOMAXPROCS on go server performance

### ISSUE THREAD

**Issue by jonhoo** [jonhoo/volley#2]
In #1, @tsenart pointed out that increasing `GOMAXPROCS` might improve the performance of the Go server significantly. This issue tracks that claim.

I'm currently running experiments with `GOMAXPROCS = 4x#CPUs` to see whether this makes a difference or not.

**Comment by tsenart** [comment]
Nice, thanks! Also, it'd be good to use the latest stable Go version: 1.4.2

**Comment by jonhoo** [comment]
Results:

![impact of increased GOMAXPROCS](https://jon.thesquareplanet.com/share/volley-go-higher-procs.png)

Seems like increasing `GOMAXPROCS` is only detrimental to the performance of the Go implementation unfortunately.

In terms of the Go version, upgrading is a bit of a pain, and as far as I can tell, nothing performance-related [changed](https://github.com/golang/go/issues?q=milestone%3AGo1.4.2) in 1.4.1 -> 1.4.2, so it shouldn't matter.

**Comment by tsenart** [comment]
Thanks for running this experiment. Would you consider sharing these
results with the Go team?

**Comment by tsenart** [comment]
By these, I mean the comparison between Go, Rust and C.

**Comment by jonhoo** [comment]
Yes, I've thought about doing that. I'd like to first run the experiment against go tip though, just to make sure that it hasn't already been fixed. Tracking in #3.
