### ISSUE TITLE
Why is the non-blocking go implementation included?

### ISSUE THREAD

**Issue by anacrolix** [jonhoo/volley#21]
I can't understand the technical reason for including the non-blocking version.

**Comment by jonhoo** [comment]
The non-blocking version is idiomatic Go, the blocking one is not. Comparing the idiomatic server implementations from different languages is interesting, and in fact, probably more so than comparing the optimized versions. The optimized versions will, in the end, have the same threads doing the same syscalls, and will probably differ very little in terms of performance.
